<a href="https://colab.research.google.com/github/Vaishalisweety/python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy 

In [1]:
import numpy as np


In [2]:
My_list=[2,4,6,8,10,12,14,16]
print(My_list)

[2, 4, 6, 8, 10, 12, 14, 16]


In [4]:
List = np.array(My_list)
print(type(List))
print(List)

<class 'numpy.ndarray'>
[ 2  4  6  8 10 12 14 16]


In [5]:
print("Size:\t" , List.size)
print("Shape:\t", List.shape)

Size:	 8
Shape:	 (8,)


In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

Multi Dim

In [12]:
Height_list = [142, 162, 177, 139, 145, 165,130,120]
print(Height_list)

[142, 162, 177, 139, 145, 165, 130, 120]


In [13]:
np.array(Height_list)

array([142, 162, 177, 139, 145, 165, 130, 120])

In [14]:
people = np.array([My_list, Height_list])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[  2   4   6   8  10  12  14  16]
 [142 162 177 139 145 165 130 120]]
Size:	 16
Shape:	 (2, 8)


In [16]:
people = people.reshape(16,1)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[  2]
 [  4]
 [  6]
 [  8]
 [ 10]
 [ 12]
 [ 14]
 [ 16]
 [142]
 [162]
 [177]
 [139]
 [145]
 [165]
 [130]
 [120]]
Size:	 16
Shape:	 (16, 1)


Exercise

In [17]:
oneD=[7, 9, 65, 33, 85, 99]
print(oneD)

[7, 9, 65, 33, 85, 99]


In [54]:
List = np.array(oneD)
print(type(List))
print(List)

<class 'numpy.ndarray'>
[ 7  9 65 33 85 99]


In [55]:
print("Size:\t" , List.size)
print("Shape:\t", List.shape)

Size:	 6
Shape:	 (6,)


In [46]:
rows, cols = (3, 3)

In [51]:
nparr = [[1, 2, 4], [2, 3, 0], [0, 5, 1]]
for i in A:
    for j in i:
        print(j,end = " ")
    print()
 

1 2 4 
2 3 0 
0 5 1 


In [56]:
people = np.array([oneD,A ])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [list([7, 9, 65, 33, 85, 99]) list([[1, 2, 4], [2, 3, 0], [0, 5, 1]])]
Size:	 2
Shape:	 (2,)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [58]:
people = people.reshape(2,1)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[list([7, 9, 65, 33, 85, 99])]
 [list([[1, 2, 4], [2, 3, 0], [0, 5, 1]])]]
Size:	 2
Shape:	 (2, 1)


Array Generation

In [60]:
five_times_table = np.arange(0, 11,2)
five_times_table

array([ 0,  2,  4,  6,  8, 10])

In [69]:
five_times_table = np.arange(0, 55, 5)
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [70]:
five_spaced = np.linspace(0,50,11)
print(five_spaced)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [61]:
five_spaced = np.linspace(0,5,10)
print(five_spaced)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [62]:
twoArr = np.repeat(2, 10)
print(twoArr)

[2 2 2 2 2 2 2 2 2 2]


In [71]:
identity_matrix = np.eye(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [63]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


operations

In [67]:
five_times_table

array([ 0,  2,  4,  6,  8, 10])

In [68]:
print("1:", 2 * five_times_table)
print("2:", 10 + five_times_table)
print("3:", five_times_table - 1)
print("4:", five_times_table/5)
print("5:", five_times_table **2)
print("6:", five_times_table < 20)

1: [ 0  4  8 12 16 20]
2: [10 12 14 16 18 20]
3: [-1  1  3  5  7  9]
4: [0.  0.4 0.8 1.2 1.6 2. ]
5: [  0   4  16  36  64 100]
6: [ True  True  True  True  True  True]


speed test

In [72]:
fives_list = list(range(0,5001,5))
fives_list

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

In [73]:
five_times_table_lge = np.arange(0,5001,5)
five_times_table_lge

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [74]:
%timeit five_times_table_lge + 5

1.75 µs ± 373 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [75]:
%timeit [e + 5 for e in fives_list]

58.9 µs ± 2.16 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [76]:
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))

print("e" in words)
["e" in word for word in words]

[False False False False False]
False


[True, True, True, True, False]

Transpose

In [80]:
ages_list = [10, 5, 8, 32, 65, 43]
print(ages_list)

[10, 5, 8, 32, 65, 43]


In [81]:
ages = np.array(ages_list)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[10  5  8 32 65 43]


In [82]:
print(ages)
print("Size:\t" , ages.size)
print("Shape:\t", ages.shape)

[10  5  8 32 65 43]
Size:	 6
Shape:	 (6,)


In [83]:
weight_list = [32, 18, 26, 60, 55, 65]

In [84]:
people = np.array([ages_list, weight_list])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10  5  8 32 65 43]
 [32 18 26 60 55 65]]
Size:	 12
Shape:	 (2, 6)


In [85]:
# 2 X 6 = 1 X 12 = 4 X 3 = 3 X 4 = 12 X 1 

people = people.reshape(12,1)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10]
 [ 5]
 [ 8]
 [32]
 [65]
 [43]
 [32]
 [18]
 [26]
 [60]
 [55]
 [65]]
Size:	 12
Shape:	 (12, 1)


In [86]:
people.shape = (2,6)
print(people, "\n")
print(people.T)

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]] 

[[10 32]
 [ 5 18]
 [ 8 26]
 [32 60]
 [65 55]
 [43 65]]


Data Types

In [87]:
people.dtype

dtype('int64')

In [88]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

In [89]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65, 43], dtype=int32)

In [90]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)

['10' '5' '8' '32' '65' '43']


In [91]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [92]:
ages_with_strings.size


126

In [93]:
ages_with_strings.size/21

6.0

In [94]:
np.array([10, 5, 8, '32', '65', '43']).size

6

In [95]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


Exercise

In [102]:
a = np.array([1,4,'2','5'], dtype = 'float')
print (a)

[1. 4. 2. 5.]


In [103]:
a.dtype = 'float'
print(a)

[1. 4. 2. 5.]


In [106]:
 array = [[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15] ]
 array = np.array(array) 
 print(array.T)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [107]:
array.shape

(3, 5)

In [108]:
array.size

15

In [114]:
array.astype (bool)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

Array Slicing Operations

In [115]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [116]:
five_times_table[0]

0

In [117]:
five_times_table[-1]

50

In [118]:
five_times_table[:4]

array([ 0,  5, 10, 15])

In [119]:
five_times_table[4:]

array([20, 25, 30, 35, 40, 45, 50])

In [120]:
print(people)
people[:3, :3]

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]]


array([[10,  5,  8],
       [32, 18, 26]])

Exercise

In [123]:
zeros = np.zeros(50)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [124]:
tworepeat=np.repeat(2,20)
print(tworepeat)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [131]:
import math
pi = math.pi
print(pi)

3.141592653589793


In [134]:
step=np.arange(0,pi, 0.1)
print(step)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1]


In [140]:
step[2:7]

array([0.2, 0.3, 0.4, 0.5, 0.6])

In [141]:
np.flip(step)

array([3.1, 3. , 2.9, 2.8, 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2. , 1.9,
       1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1, 1. , 0.9, 0.8, 0.7, 0.6,
       0.5, 0.4, 0.3, 0.2, 0.1, 0. ])

In [143]:
step[0::4]

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8])

In [144]:
step[::-2]

array([3.1, 2.9, 2.7, 2.5, 2.3, 2.1, 1.9, 1.7, 1.5, 1.3, 1.1, 0.9, 0.7,
       0.5, 0.3, 0.1])

In [145]:
step[-3:]

array([2.9, 3. , 3.1])

In [146]:
step [4:8]

array([0.4, 0.5, 0.6, 0.7])

In [147]:
reverse_five_times_table = np.flip(five_times_table)
reverse_five_times_table

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [148]:
reverse_five_times_table = five_times_table[-1::-1]
print(reverse_five_times_table)
five_times_table

[50 45 40 35 30 25 20 15 10  5  0]


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [149]:
five_times_table[0::3] #Every 3rd element starting from 0

array([ 0, 15, 30, 45])

In [150]:
reverse=np.flip(step)
print(reverse)

[3.1 3.  2.9 2.8 2.7 2.6 2.5 2.4 2.3 2.2 2.1 2.  1.9 1.8 1.7 1.6 1.5 1.4
 1.3 1.2 1.1 1.  0.9 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1 0. ]


In [151]:
step [-1::-2]

array([3.1, 2.9, 2.7, 2.5, 2.3, 2.1, 1.9, 1.7, 1.5, 1.3, 1.1, 0.9, 0.7,
       0.5, 0.3, 0.1])

Stats

In [152]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [153]:
nums = np.arange(0, 4, 0.2555)

Exercise

Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [154]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


Random

In [155]:
flip = np.random.choice([0,1], 10)
flip

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 1])

In [156]:
np.random.rand(10,20,9)

array([[[3.01855505e-01, 1.12840227e-01, 2.44210002e-01, ...,
         3.43805202e-01, 2.50339459e-01, 5.97417820e-02],
        [9.38316067e-01, 1.96030470e-01, 4.04524559e-01, ...,
         8.83310496e-01, 4.09541196e-01, 8.87732057e-01],
        [3.40467366e-01, 5.54405324e-01, 1.59681457e-01, ...,
         5.12709878e-02, 4.69490837e-01, 8.42560961e-01],
        ...,
        [6.04408977e-01, 1.81746718e-01, 9.86177715e-01, ...,
         6.12863594e-01, 9.18288790e-01, 4.69414386e-01],
        [7.83317631e-01, 4.72397657e-02, 9.56873567e-01, ...,
         8.73320536e-01, 7.89879912e-01, 9.28957642e-01],
        [3.57013185e-01, 9.86126700e-01, 7.41090400e-01, ...,
         5.15090280e-01, 5.54520594e-01, 3.55912736e-01]],

       [[1.82012686e-01, 9.09775581e-01, 7.81000318e-01, ...,
         2.82670955e-01, 3.17659061e-01, 6.58929854e-01],
        [9.71354409e-01, 6.68857252e-01, 1.68685177e-01, ...,
         7.65582357e-01, 8.56768429e-01, 4.60038389e-01],
        [2.84438652e-01, 

In [158]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)
print(mu)
print(sigma)
print(s)

0
0.1
[ 0.10323524 -0.11010251 -0.04870383 -0.06562065  0.20345337 -0.01571871
 -0.16283329 -0.03353554  0.02625057  0.02344505  0.03131469 -0.02093281
 -0.00690974  0.06218255  0.07968657 -0.09172237 -0.1110662  -0.1584871
  0.08700255 -0.02315226  0.04837231  0.12907828  0.01726459  0.00037543
  0.02884846 -0.01690324 -0.12488405  0.02056682 -0.02014139 -0.10488523
  0.04821572 -0.07716336  0.01211045 -0.05292948 -0.22815718  0.07104581
  0.11292014  0.01182206 -0.10538928  0.1243389  -0.04174928 -0.05168908
  0.16878022  0.02440958 -0.14640769 -0.15160318  0.0299887   0.06625735
  0.00586245  0.10184999  0.0271962   0.12928459  0.13604715 -0.04209463
 -0.00331904 -0.02206964  0.03966742  0.01929789  0.11553537 -0.1108316
 -0.036862    0.07280026  0.12072721  0.10546026 -0.13701462 -0.18684701
  0.18207052 -0.15145912 -0.1263768   0.10830631 -0.05338268 -0.09193712
  0.05733453  0.03070841  0.07313384 -0.05477835  0.09889032  0.03939133
  0.0937427  -0.02595259  0.18490602  0.0886664

Exercise

In [159]:
dice = np.random.choice([0,1,2,3,4,5,6], 10)
dice

array([5, 6, 2, 4, 0, 2, 0, 2, 5, 5])

In [160]:
notfair = np.random.choice([0,1,1], 10)
notfair

array([1, 1, 1, 0, 0, 0, 1, 1, 0, 0])